### ISSUE TITLE
Add affordance for raising RunTime Messages/Errors in WorkerInstance

### ISSUE THREAD

**Issue by philipbelesky** [specklesystems/GrasshopperAsyncComponent#14]
Thanks again for creating and documenting such a reliable approach to doing async work in Grasshopper!

I'm still mostly getting a handle on how to use this approach, but it seems like because classes derived from `WorkerInstance` effectively handle `RegisterInputParams` through `GetData`, it is no longer possible to add a `AddRuntimeMessage` or `AddRuntimeWarning` (because it is not inheriting from `GH_Component`). As a result, you loose the ability to do add warnings/messages in response to bad input data, or as part of what would normally be `SolveInstance`. (This is, unless I'm missing anything)

Ideally, there would be a method in `WorkerInstance` that allows for these kind of messages to be bubbled up to a `GH_AsyncComponent` although I'm not sure if this kind of message passing would work well. I'll likely have a go at this over the next couple of weeks as part of a plugin that begins to use more async components.

This possibly related to whatever implementation addresses #11

**Comment by AlanRynne** [comment]
Hi Philip! Thanks for reporting this and yes, it is totally related to issue #11 👍🏻 . There is a way to do this, which is how we are dealing with the problem ourselves for now, for lack of a more consistent solution.

The `WorkerInstance` has a constructor that requires you to pass in the `Parent` component.

https://github.com/specklesystems/GrasshopperAsyncComponent/blob/57c7dd0bd008b0cc672342e31dd46cf44a9b0479/GrasshopperAsyncComponent/WorkerInstance.cs#L33

You can use that Parent reference to call `Parent.AddRuntimeMessage()` anytime you want. This has some limitations as it may "swallow" some of the runtime messages you may want to display. Our fast and dirty solution to this is to create a `RuntimeMessages` property in the worker of choice, and delay the messages until the end of the component lifecycle (when `SetData` is called). See the `CreateSpeckleObject` node of our GH Connector for example.

https://github.com/specklesystems/speckle-sharp/blob/09608cae6fbb53b564915e9ccce030eca4267e59/ConnectorGrasshopper/ConnectorGrasshopper/Objects/CreateSpeckleObjectAsync.cs#L181-L194

I'm closing this issue to prevent duplication but feel free to report back in #11 if you have any issues. We'd also welcome feedback on how this "error  reporting" mechanism should ideally work :)

**Comment by philipbelesky** [comment]
Sorry for the delayed reply, I missed the notification. Thanks for your explanation and for the example!
