### ISSUE TITLE
When chained together downstream components calculate multiple times

### ISSUE THREAD

**Issue by HughGrovesArup** [specklesystems/GrasshopperAsyncComponent#3]
Not sure if this is solvable within Grasshopper 1.0, but when chained together the downstream components end up calculating multiple times.

![repeats gif](https://user-images.githubusercontent.com/40033911/95359566-3ae9a380-08c2-11eb-9622-7e1060b95433.gif)

This is probably a blocker for what I would want to use this for. I imagine I will need to implement a UI blocking method instead. Does anyone know how I might do that? Just adding `.Result` to my asynchronous method seems to lead to a dead lock?

I looked at TaskCapable but that seems to be for parallel? I guess just running one Task is also acceptable?

(P.S. Thanks for open-sourcing this Dimitrie, great to see projects out in the open!)

**Comment by didimitrie** [comment]
Hey @HughGrovesArup! Yes, this behaviour is expected as we're bypassing/hacking around GH's built in solver. Not sure what your use case is, nevertheless the downstream component, it doesn't really run *twice* (unless the calc inside is fast) - it starts running, then if it gets another input, it will cancel its previous tasks and start with the fresh input. I guess if it's for collecting time series of data, yes, it's not going to work, as you are going to get incomplete/garbage states. 

Apparently @AlanRynne has looked into this a bit, more tomorrow! 

I've flagged this as a question for now as I'm not sure there's a real solution, as you've mentioned :)

**Comment by HughGrovesArup** [comment]
Had forgotten about the cancellation, that's a really good point!

**Comment by didimitrie** [comment]
closed this and #2 as we've got it to probably the best where we can get it, ie. no more null data flashes until component is ready to set the updated inputs: 

![lookmanoflash-2](https://user-images.githubusercontent.com/7696515/95596003-bbd0a880-0a44-11eb-90df-044b18dcc019.gif)
