### ISSUE TITLE
List<T> data format input

### ISSUE THREAD

**Issue by davilinhit** [specklesystems/GrasshopperAsyncComponent#9]
Dear Author,
Thanks very much for your kind AsyncComponent. I have tested all the files and found that it's run well with item data.
Now, i want to develop a async compoent for mesh geodesic curves calculation. 
two List<Point3d> data will input the component, and I fond that the above asyncComponent is not suitable for List<T>.
Do you know how to solve this issuse？

**Comment by didimitrie** [comment]
Hey @davilinhit, thanks for asking this! You can see some implementations of how we work with lists in the Speckle repo for [grasshopper here](https://github.com/specklesystems/speckle-sharp/tree/master/ConnectorGrasshopper). 

Data matching is becoming a bit of a problem in this cases, but shouldn't be unsurmountable. What the component is doing behind the scenes is actually working with the iterations that gh would do natively, so you can write your logic accordingly. 

I'll close this issue now, but in case you're still interested (this reply comes really late), we can keep conversing here.
